version: '2'

services:
  app:
    image: 'modularbank-demo:latest'
    build:
      context: .
    container_name: app
    ports:
      - '80:8080'
    depends_on:
      - db
      - rabbit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/modularbank??characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=modularbank
      - SPRING_DATASOURCE_PASSWORD=modularbank
      - SPRING_RABBITMQ_HOST=rabbit
          
  db:
    image: 'postgres:13.3-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=modularbank
      - POSTGRES_PASSWORD=modularbank
      - POSTGRES_DB=modularbank
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql

  rabbit:
    image: 'rabbitmq:management-alpine'
    container_name: rabbit
    ports:
#      - 5672:5672
      - 15672:15672